version: '3.8'
service:
  my-web-app:
    container_name: my-web-app
    build: ./app
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 5000:5000
#    version:
#      - '0.0.1'
#    restart: always
    networks:
      - docker_app_network

networks:
  docker_app_network:
    external: true